export class MockData {
  get() {
    return [
    {
      "id": "66d7544d9e6170f336327ecf",
      "first_name": "Benita",
      "last_name": "Crane",
      "email": "benita@incubus.kz",
      "username": "benita88",
      "company": "Incubus",
      "dob": "1988-12-30",
      "address": "93 Woodrow Court, Berwind, Iowa",
      "available": true
    },
    {
      "id": "66d7544da2535f18125bb11e",
      "first_name": "Annmarie",
      "last_name": "Shepard",
      "email": "annmarie@rockyard.fail",
      "username": "annmarie93",
      "company": "Rockyard",
      "dob": "1993-04-15",
      "address": "90 Dinsmore Place, Norfolk, Colorado",
      "available": true
    },
    {
      "id": "66d7544df1c8ed6bbd3cbe79",
      "first_name": "Lidia",
      "last_name": "Moore",
      "email": "lidia@eventex.cash",
      "username": "lidia92",
      "company": "Eventex",
      "dob": "1992-01-15",
      "address": "81 Covert Street, Frierson, Mississippi",
      "available": false
    },
    {
      "id": "66d7544df9fcde24c1e0b040",
      "first_name": "Garcia",
      "last_name": "Decker",
      "email": "garcia@nutralab.delivery",
      "username": "garcia89",
      "company": "Nutralab",
      "dob": "1989-09-13",
      "address": "32 Bond Street, Trexlertown, Alaska",
      "available": false
    },
    {
      "id": "66d7544de029d30b47a35377",
      "first_name": "Carissa",
      "last_name": "Conner",
      "email": "carissa@limozen.mtn",
      "username": "carissa91",
      "company": "Limozen",
      "dob": "1991-07-20",
      "address": "56 Dooley Street, Darbydale, Northern Mariana Islands",
      "available": true
    },
    {
      "id": "66d7544dd57ca6c3af18e6e6",
      "first_name": "Lou",
      "last_name": "Mullins",
      "email": "lou@portica.se",
      "username": "lou93",
      "company": "Portica",
      "dob": "1993-02-25",
      "address": "30 Polhemus Place, Soudan, California",
      "available": true
    },
    {
      "id": "66d7544d439515ef15ee4d90",
      "first_name": "Roxanne",
      "last_name": "Norman",
      "email": "roxanne@dreamia.ec",
      "username": "roxanne90",
      "company": "Dreamia",
      "dob": "1990-10-14",
      "address": "42 Lee Avenue, Brecon, Ohio",
      "available": true
    },
    {
      "id": "66d7544dfd15083457563bfa",
      "first_name": "Merle",
      "last_name": "Ballard",
      "email": "merle@renovize.su",
      "username": "merle94",
      "company": "Renovize",
      "dob": "1994-09-17",
      "address": "15 George Street, Springdale, District Of Columbia",
      "available": true
    },
    {
      "id": "66d7544da39fad1ec85b9dfb",
      "first_name": "Farley",
      "last_name": "Gibbs",
      "email": "farley@netagy.limo",
      "username": "farley92",
      "company": "Netagy",
      "dob": "1992-03-08",
      "address": "92 Seaview Court, Dargan, Missouri",
      "available": false
    },
    {
      "id": "66d7544d2c1ca98e2e0a0db5",
      "first_name": "Randolph",
      "last_name": "Mercado",
      "email": "randolph@megall.um",
      "username": "randolph90",
      "company": "Megall",
      "dob": "1990-08-20",
      "address": "60 Congress Street, Wikieup, American Samoa",
      "available": true
    },
    {
      "id": "66d7544d9e806fd36400566f",
      "first_name": "Chaney",
      "last_name": "Whitney",
      "email": "chaney@eternis.ceo",
      "username": "chaney92",
      "company": "Eternis",
      "dob": "1992-11-15",
      "address": "16 Riverdale Avenue, Mathews, Alabama",
      "available": false
    },
    {
      "id": "66d7544dbadb229b8c456efd",
      "first_name": "Myrna",
      "last_name": "Castaneda",
      "email": "myrna@senmao.blackfriday",
      "username": "myrna92",
      "company": "Senmao",
      "dob": "1992-03-01",
      "address": "84 Love Lane, Emerald, Georgia",
      "available": true
    },
    {
      "id": "66d7544db801ab1f962a4138",
      "first_name": "Kelly",
      "last_name": "Martinez",
      "email": "kelly@papricut.properties",
      "username": "kelly90",
      "company": "Papricut",
      "dob": "1990-04-23",
      "address": "3 Sedgwick Place, Templeton, Minnesota",
      "available": true
    },
    {
      "id": "66d7544dc243fb3ee50965c6",
      "first_name": "Marian",
      "last_name": "Cochran",
      "email": "marian@gleamink.glass",
      "username": "marian90",
      "company": "Gleamink",
      "dob": "1990-10-29",
      "address": "86 Campus Road, Succasunna, Delaware",
      "available": true
    },
    {
      "id": "66d7544d7736e4dd85e14f1e",
      "first_name": "Cara",
      "last_name": "Campos",
      "email": "cara@cytrek.sew",
      "username": "cara88",
      "company": "Cytrek",
      "dob": "1988-05-31",
      "address": "73 Himrod Street, Rosburg, Tennessee",
      "available": true
    },
    {
      "id": "66d7544d2125c078f7894f38",
      "first_name": "Hess",
      "last_name": "Sargent",
      "email": "hess@spherix.dance",
      "username": "hess92",
      "company": "Spherix",
      "dob": "1992-09-02",
      "address": "53 Chestnut Street, Whitmer, West Virginia",
      "available": true
    },
    {
      "id": "66d7544d594dc4a293995035",
      "first_name": "Delores",
      "last_name": "Oneil",
      "email": "delores@corecom.firmdale",
      "username": "delores88",
      "company": "Corecom",
      "dob": "1988-10-18",
      "address": "61 Willoughby Street, Villarreal, Texas",
      "available": true
    },
    {
      "id": "66d7544d9440a69704aa6082",
      "first_name": "Mcneil",
      "last_name": "Hines",
      "email": "mcneil@artiq.ee",
      "username": "mcneil93",
      "company": "Artiq",
      "dob": "1993-07-19",
      "address": "24 Hale Avenue, Monument, Pennsylvania",
      "available": true
    },
    {
      "id": "66d7544d2b7513ce9a3e5772",
      "first_name": "Mitchell",
      "last_name": "Herman",
      "email": "mitchell@endipine.ing",
      "username": "mitchell94",
      "company": "Endipine",
      "dob": "1994-08-14",
      "address": "16 Dorchester Road, Leeper, Virginia",
      "available": false
    },
    {
      "id": "66d7544d4fc17cbcc294f13a",
      "first_name": "Mccarthy",
      "last_name": "Cantu",
      "email": "mccarthy@moreganic.azure",
      "username": "mccarthy89",
      "company": "Moreganic",
      "dob": "1989-08-03",
      "address": "27 Lafayette Avenue, Foscoe, Arkansas",
      "available": true
    },
    {
      "id": "66d7544db583323cba24a960",
      "first_name": "Gilda",
      "last_name": "Pace",
      "email": "gilda@miraclis.hu",
      "username": "gilda89",
      "company": "Miraclis",
      "dob": "1989-06-25",
      "address": "80 Hoyts Lane, Volta, Marshall Islands",
      "available": true
    },
    {
      "id": "66d7544da0e740037ad55734",
      "first_name": "Hunter",
      "last_name": "Pollard",
      "email": "hunter@digique.mo",
      "username": "hunter91",
      "company": "Digique",
      "dob": "1991-12-04",
      "address": "8 Heyward Street, Riner, Oklahoma",
      "available": true
    },
    {
      "id": "66d7544da746319b6561c68f",
      "first_name": "Cardenas",
      "last_name": "Daniels",
      "email": "cardenas@cubicide.new",
      "username": "cardenas88",
      "company": "Cubicide",
      "dob": "1988-05-28",
      "address": "31 Stoddard Place, Choctaw, Guam",
      "available": true
    },
    {
      "id": "66d7544d1f11ac8527067ca2",
      "first_name": "Rivera",
      "last_name": "Weeks",
      "email": "rivera@acruex.guru",
      "username": "rivera88",
      "company": "Acruex",
      "dob": "1988-12-20",
      "address": "19 Macon Street, Glendale, South Dakota",
      "available": true
    },
    {
      "id": "66d7544dc3c44f72268f1590",
      "first_name": "Louella",
      "last_name": "Marsh",
      "email": "louella@zomboid.gov",
      "username": "louella94",
      "company": "Zomboid",
      "dob": "1994-07-31",
      "address": "94 Onderdonk Avenue, Rehrersburg, Hawaii",
      "available": true
    },
    {
      "id": "66d7544deed338b334d81501",
      "first_name": "Weber",
      "last_name": "Marks",
      "email": "weber@stralum.solutions",
      "username": "weber94",
      "company": "Stralum",
      "dob": "1994-09-11",
      "address": "29 Concord Street, Wilsonia, Indiana",
      "available": true
    },
    {
      "id": "66d7544de23ab859fd4f6745",
      "first_name": "Perry",
      "last_name": "Chandler",
      "email": "perry@kenegy.cologne",
      "username": "perry89",
      "company": "Kenegy",
      "dob": "1989-04-10",
      "address": "88 Cozine Avenue, Stewartville, Idaho",
      "available": true
    },
    {
      "id": "66d7544d18ea01ff6f75ddfd",
      "first_name": "Harmon",
      "last_name": "Eaton",
      "email": "harmon@zoarere.boutique",
      "username": "harmon89",
      "company": "Zoarere",
      "dob": "1989-03-30",
      "address": "63 Herbert Street, Ola, Maine",
      "available": true
    },
    {
      "id": "66d7544d425c559c4f7d85ff",
      "first_name": "Sheri",
      "last_name": "Knight",
      "email": "sheri@mangelica.onl",
      "username": "sheri93",
      "company": "Mangelica",
      "dob": "1993-07-14",
      "address": "69 Portal Street, Linwood, Nebraska",
      "available": true
    },
    {
      "id": "66d7544d7e565c264b6b8ec0",
      "first_name": "Tanner",
      "last_name": "Page",
      "email": "tanner@geekular.memorial",
      "username": "tanner94",
      "company": "Geekular",
      "dob": "1994-08-01",
      "address": "21 Montana Place, Topanga, Michigan",
      "available": true
    },
    {
      "id": "66d7544d32eb5fdc0ad2d9a8",
      "first_name": "Hahn",
      "last_name": "Rivera",
      "email": "hahn@isoternia.allfinanz",
      "username": "hahn91",
      "company": "Isoternia",
      "dob": "1991-01-21",
      "address": "12 Elton Street, Brazos, Illinois",
      "available": true
    },
    {
      "id": "66d7544d655590538518ed35",
      "first_name": "Fernandez",
      "last_name": "Cote",
      "email": "fernandez@zentime.express",
      "username": "fernandez89",
      "company": "Zentime",
      "dob": "1989-02-26",
      "address": "100 Metrotech Courtr, Kylertown, Kansas",
      "available": true
    },
    {
      "id": "66d7544d3e387e886f4cb06b",
      "first_name": "Davenport",
      "last_name": "Atkins",
      "email": "davenport@techtrix.mormon",
      "username": "davenport89",
      "company": "Techtrix",
      "dob": "1989-09-20",
      "address": "74 Fulton Street, Brady, New York",
      "available": true
    },
    {
      "id": "66d7544df4a9e6e4ef259e96",
      "first_name": "Craig",
      "last_name": "Burton",
      "email": "craig@comstruct.jll",
      "username": "craig91",
      "company": "Comstruct",
      "dob": "1991-07-13",
      "address": "53 Chester Court, Keyport, North Dakota",
      "available": true
    },
    {
      "id": "66d7544d9632d428a592f365",
      "first_name": "Aileen",
      "last_name": "Chase",
      "email": "aileen@earwax.diet",
      "username": "aileen92",
      "company": "Earwax",
      "dob": "1992-08-14",
      "address": "64 Merit Court, Malott, Washington",
      "available": true
    },
    {
      "id": "66d7544da47cc3a89b30029c",
      "first_name": "Lucia",
      "last_name": "Rollins",
      "email": "lucia@affluex.online",
      "username": "lucia94",
      "company": "Affluex",
      "dob": "1994-12-03",
      "address": "73 Neptune Avenue, Smock, Vermont",
      "available": true
    },
    {
      "id": "66d7544d924e96f3a3e5609f",
      "first_name": "Lavonne",
      "last_name": "Sanchez",
      "email": "lavonne@uberlux.rio",
      "username": "lavonne94",
      "company": "Uberlux",
      "dob": "1994-11-14",
      "address": "4 Cypress Avenue, Alamo, South Carolina",
      "available": true
    },
    {
      "id": "66d7544d577fc0b9c2fa1e31",
      "first_name": "Cunningham",
      "last_name": "Calhoun",
      "email": "cunningham@solaren.gmo",
      "username": "cunningham91",
      "company": "Solaren",
      "dob": "1991-03-20",
      "address": "30 Holt Court, Motley, North Carolina",
      "available": true
    },
    {
      "id": "66d7544d389e35bf08b5ff80",
      "first_name": "Gillespie",
      "last_name": "Holden",
      "email": "gillespie@centice.horse",
      "username": "gillespie94",
      "company": "Centice",
      "dob": "1994-12-31",
      "address": "21 Osborn Street, Rosedale, Florida",
      "available": true
    },
    {
      "id": "66d7544dc6100a10509cc1a0",
      "first_name": "Kramer",
      "last_name": "Cohen",
      "email": "kramer@emtrak.science",
      "username": "kramer89",
      "company": "Emtrak",
      "dob": "1989-08-11",
      "address": "68 Gem Street, Madrid, Palau",
      "available": true
    }
  ]}
}